### ISSUE TITLE
Add the plugin to the WordPress.org plugin directory

### ISSUE THREAD

**Issue by akirk** [Automattic/wp-openid-connect-server#25]
Final step for completing https://github.com/Automattic/wp-openid-connect-server/milestones/1

**Comment by ashfame** [comment]
- [x] Ran the readme file via [readme validator](https://wordpress.org/plugins/developers/readme-validator/?readme=https%3A%2F%2Fraw.githubusercontent.com%2FAutomattic%2Fwp-openid-connect-server%2Fmain%2Freadme.txt) but it didn't warn about other that missing sections that are not relevant for a new release.
- [ ] #52 
- [ ] #53
- [ ] #54 
- [ ] Tag v1.0 on Github

@akirk @psrpinto 
One last thing, I am wondering is, do we want to publish this plugin under its current name since once published it would receive a permanent slug for it? It actually would be a good time to change its name to represent that its infact an OAuth server which includes support for OIDC and then later on it would eventually end up covering more of the OAuth spec. Thoughts?

**Comment by psrpinto** [comment]
I don't have strong feelings about keeping the name or renaming to something that would not clash were this plugin to move towards also doing OAuth stuff. I don't know much about the differences between OIDC and OAuth.

If we end up sticking to the OIDC-related name, one sugestion I would make would be to shorten it, for example `wp-oidc-server`, I find the name too long to type :D

----
I'm curious how we're planning to bring the plugin to wporg, from a technical perspective, i.e. what's the process you envision for bringing a release on GitHub to wporg?

**Comment by ashfame** [comment]
@psrpinto To give you some context, OIDC is a simple identity layer on top of the OAuth 2.0 protocol. Right now, we have most of OAuth stuff, which was required for OIDC but for the canonical plugins vision where more of OAuth stuff would be needed, it might be better to brand this plugin as OAuth server supporting OIDC as well. Otherwise, in future, it would be confusing that plugin is called OIDC but it does normal OAuth stuff as well.

This is the reason for my prompt regarding renaming the plugin now.

> I'm curious how we're planning to bring the plugin to wporg, from a technical perspective, i.e. what's the process you envision for bringing a release on GitHub to wporg?

For the first release, I would just tag it on Github and upload it manually since first submission required review + approval. Once first version is live, then we can consider automating it in some fashion since only then we can release on our own using svn.

**Comment by ashfame** [comment]
Plugin submitted to WP.org official plugins repo. Would be available on https://wordpress.org/plugins/search/openid-connect-server/ when approved.
