### ISSUE TITLE
Storing authorization codes in taxonomy might mean that users can access other users' authorization codes

### ISSUE THREAD

**Issue by psrpinto** [Automattic/wp-openid-connect-server#26]
We need to research this for vulnerabilities. Should also make sure Taxonomy is not accessible via REST API.

**Comment by ashfame** [comment]
I looked into this. When we [register taxonomy](https://developer.wordpress.org/reference/functions/register_taxonomy/), default configuration is to be hidden from rest api. It becomes available on rest api only when we register taxonomy like:

`register_taxonomy( self::TAXONOMY, null, array( 'show_in_rest' => true ) );`

Same goes with term meta:

```
register_term_meta(
	self::TAXONOMY,
	$key,
	array(
		'type'              => $type,
		'single'            => true,
		'sanitize_callback' => array( __CLASS__, 'sanitize_' . $key ),
		'show_in_rest' => true,
	)
);
```

Since we need to protect the term name itself, we are fine as is 👍 

I tested by enabling `show_in_rest` and terms and their meta showed up on REST api. So, it's safe to close this.

**Comment by psrpinto** [comment]
Thanks for looking into this :) To be clear, whether the taxonomy shows in the REST API is only one of the aspects of this issue.

The main problem, I believe, is that all users can access the taxonomy, which means user A can access user's B authorization codes, which could allow user A to impersonate user B.

Assuming the above is correct, the solution would be to store authorization codes on user level, i.e. user meta or similar, so that only the owner of the authorization code can access it.

**Comment by ashfame** [comment]
> The main problem, I believe, is that all users can access the taxonomy, which means user A can access user's B authorization codes, which could allow user A to impersonate user B.

I understand where you coming from that since these are not tied up to any user, there is no protection for not letting someone access which don't belong to them.

I can't think of anyway this could be exposed since we are not attaching taxonomy to any custom post type. See second argument `null` for register_taxonomy. So, this will not get exposed on its own anywhere in the UI. 

Technically, these are as good as usermeta since by default user meta fields are also not available on rest api and you have to explicitly make each usermeta available. So both options seem to be equivalent in terms of being safe.

That being said, storing data in taxonomy does seem odd and usermeta sounds like a better place to store it. Plus the likelihood of usermeta being treated with more caution could be the reason for our switch.

**Comment by ashfame** [comment]
@akirk Did you get a chance to look into this yet, as you mentioned? We need to figure out our next steps here. Happy to do the required digging. Let me know.

**Comment by ashfame** [comment]
Another bit that I noticed against taxonomy storage is many entries are left in terms table (for abandoned/interrupted SSO logins), and there is no clean way to differentiate these with actual terms stored.

![Screenshot 2022-09-29 at 2 11 10 PM](https://user-images.githubusercontent.com/858906/193004735-02ae17be-5af9-4865-8b3a-30d8781c2b9e.png)

**Comment by akirk** [comment]
We need to set some parameters for `register_taxonomy`, importantly:
```
array(
    'public' => false,
    'show_ui' => false,
)
```

Another option that we considered is to use user_meta. One reason we initially decided against it is that we need to query all users by the key which we found out can be done using a command like this:
```
get_users(array(
    'meta_key' => 'openid_connect_code',
    'meta_value' => '098f6bcd4621d373cade4e832627b4f6'
))
```
