### ISSUE TITLE
Add a filter for retrieving the authorization code

### ISSUE THREAD

**Issue by akirk** [Automattic/wp-openid-connect-server#51]
In https://github.com/Automattic/wp-openid-connect-server/blob/main/src/Storage/AuthorizationCodeStorage.php#L27 we use `get_users()` to find a user who possesses the `authorization_code` being provided.

This fails on WordPress.org because the user is not a member of the main wordpress.org site. This can be resolved by adding a `'blog_id' => 0`. I think it is reasonably to use the implied default of `'blog_id' => get_current_site_id()` here, so a viable approach would be to allow overriding the parameters with a filter.

So something like
```
$users = get_users(
	apply_filters( 'oidc_authorization_code_query',
		array(
			'number'       => 1,
			// phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_meta_key
			'meta_key'     => self::META_KEY_PREFIX . '_client_id_' . $code,
			// Using a meta_key EXISTS query is not slow, see https://github.com/WordPress/WordPress-Coding-Standards/issues/1871.
			'meta_compare' => 'EXISTS',
		)
	)
);
```

Also, could we remove the comment mentioning me, I don't think it provides a lot of value since it is a general rule to use a WordPress function over a direct db query where possible.

**Comment by ashfame** [comment]
I am not sure I fully understand this, primarily because I don't understand Multisite that well. I think we should try to do it in a way that our plugin handles itself in a Multisite install in an expected manner and only offer a filter to do something custom.

A filter to account for Multisite installs is better handled within the plugin itself without having to provide a filter. That being said, we should try to find what do we need to do in order to make it MS compatible and what does MS compatible even mean for our plugin?

In this issue's context, we care to search for all users on the install and not just specific to a site in MS, so that's why we want to specify `blog_id = 0` for a global user search, right?

Why don't we just do it right here?

`'blog_id' => is_multisite() ? 0 : get_current_blog_id()`

Would this not work?

**Comment by ashfame** [comment]
So what I am gathering is, the proper behaviour for Multisite should be all sites are independent of each other (WP.com approach as you put it), which is obviously not supported by our plugin, since we are not creating endpoints for all sites under a MS, just on the primary site's url.

In this case, we could just include the `blog_id` as `get_current_blog_id()` when fetching for `get_users()` and that would include only the members of the current site.

WP.org approach is the exception on top of this proper MS behavior, in which sites are not independent and it could be the case all users are part of a single site (which doesn't have to be the primary site of blog_id=1 and which is why we need to allow the possibility of blog_id to be overriden. We would also need a way to disable endpoints across all sites. But this entire WP.org usecase is easily handled by selectively enabling the plugin on a specific site where we want the endpoints and override the `blog_id` used in `get_users()` call.

Would you say, that's correct to state? Is that how we are planning to enable this plugin on WP.org?

Also, I am wondering if the filter should be on all arguments or just the blog_id argument?

**Comment by akirk** [comment]
I agree with your summary. I don't think it's necessary to specify the `blog_id` parameter since it's added automatically for multisites and we'd need an exception for non-multisites.

I don't see what the benefit for limiting the filter to the `blog_id` entry of the array, maybe someone would want to modify other options, e.g. limit it to users with a certain e-mail address domain.

Thus, I stand by my approach in https://github.com/Automattic/wp-openid-connect-server/pull/52.

**Comment by ashfame** [comment]
I like the idea of specifying `blog_id` and provide a filter on top of that so it's specific to that customisation need for unusual MS installs.

I can't justify anyone wanting to modify the users query this late to limit the users for whom OIDC is available. That's got to be very early on, even before we present them a consent screen.

I just tested and `blog_id` on a non-MS does nothing to `get_users()` call so I would say this looks better to me:

```
$users = get_users(
	array(
		'number'       => 1,
		// This does nothing for non-MultiSite installs. But for MultiSite installs, it allows you to customize users of which site is supposed to be available for whatever sites this plugin is meant for
		'blog_id'	   => apply_filters( 'oidc_auth_code_storage_blog_id', get_current_blog_id() ),
		// phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_meta_key
		'meta_key'     => self::META_KEY_PREFIX . '_client_id_' . $code,
		// Using a meta_key EXISTS query is not slow, see https://github.com/WordPress/WordPress-Coding-Standards/issues/1871.
		'meta_compare' => 'EXISTS',
	)
);
```

Thoughts?

**Comment by akirk** [comment]
I believe in the versatility I suggested but your suggestion is ok, too.
