### ISSUE TITLE
Make .well-known URLs work with subdirectory installs

### ISSUE THREAD

**Issue by akirk** [Automattic/wp-openid-connect-server#6]

**Comment by ashfame** [comment]
> Well-known URIs are rooted in the top of the path's hierarchy; they
   are not well-known by definition in other parts of the path.  For
   example, "/.well-known/example" is a well-known URI, whereas
   "/foo/.well-known/example" is not.

The only fix we can have is to be functional on a non-standard uri such as `/foo/.well-known/jwks.json` since that would be outside of WordPress perspective to control. This way atleast the endpoint is available and the website admin can make it available on root, if desired.
